---
- name: Download Zabbix release .deb package
  get_url:
    url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-3+ubuntu20.04_all.deb
    dest: /tmp/zabbix-release.deb

- name: Install Zabbix release package
  apt:
    deb: /tmp/zabbix-release.deb
    state: present

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install Zabbix agent
  apt:
    name: zabbix-agent
    state: present

#- name: Copy Zabbix agent config
#  template:
#    src: zabbix_agentd.conf.j2
#    dest: /etc/zabbix/zabbix_agentd.conf
#    owner: root
#    group: root
#    mode: '0644'

- name: Enable and start Zabbix agent
  service:
    name: zabbix-agent
    state: started
    enabled: yes
